insert into countries values (1, 'AF', 'Afghanistan');
insert into countries values (2, 'AL', 'Albania');
insert into countries values (3, 'DZ', 'Algeria');
insert into countries values (4, 'AS', 'American Samoa');
insert into countries values (5, 'AD', 'Andorra');
insert into countries values (6, 'AO', 'Angola');
insert into countries values (7, 'AI', 'Anguilla');
insert into countries values (8, 'AQ', 'Antarctica');
insert into countries values (9, 'AG', 'Antigua and Barbuda');
insert into countries values (10, 'AR', 'Argentina');
insert into countries values (11, 'AM', 'Armenia');
insert into countries values (12, 'AW', 'Aruba');
insert into countries values (13, 'AU', 'Australia');
insert into countries values (14, 'AT', 'Austria');
insert into countries values (15, 'AZ', 'Azerbaijan');
insert into countries values (16, 'BS', 'Bahamas');
insert into countries values (17, 'BH', 'Bahrain');
insert into countries values (18, 'BD', 'Bangladesh');
insert into countries values (19, 'BB', 'Barbados');
insert into countries values (20, 'BY', 'Belarus');
insert into countries values (21, 'BE', 'Belgium');
insert into countries values (22, 'BZ', 'Belize');
insert into countries values (23, 'BJ', 'Benin');
insert into countries values (24, 'BM', 'Bermuda');
insert into countries values (25, 'BT', 'Bhutan');
insert into countries values (26, 'BO', 'Bolivia');
insert into countries values (27, 'BA', 'Bosnia and Herzegovina');
insert into countries values (28, 'BW', 'Botswana');
insert into countries values (29, 'BV', 'Bouvet Island');
insert into countries values (30, 'BR', 'Brazil');
insert into countries values (31, 'IO', 'British Indian Ocean Territory');
insert into countries values (32, 'BN', 'Brunei Darussalam');
insert into countries values (33, 'BG', 'Bulgaria');
insert into countries values (34, 'BF', 'Burkina Faso');
insert into countries values (35, 'BI', 'Burundi');
insert into countries values (36, 'KH', 'Cambodia');
insert into countries values (37, 'CM', 'Cameroon');
insert into countries values (38, 'CA', 'Canada');
insert into countries values (39, 'CV', 'Cape Verde');
insert into countries values (40, 'KY', 'Cayman Islands');
insert into countries values (41, 'CF', 'Central African Republic');
insert into countries values (42, 'TD', 'Chad');
insert into countries values (43, 'CL', 'Chile');
insert into countries values (44, 'CN', 'China');
insert into countries values (45, 'CX', 'Christmas Island');
insert into countries values (46, 'CC', 'Cocos (Keeling Islands)');
insert into countries values (47, 'CO', 'Colombia');
insert into countries values (48, 'KM', 'Comoros');
insert into countries values (49, 'CG', 'Congo');
insert into countries values (50, 'CK', 'Cook Islands');
insert into countries values (51, 'CR', 'Costa Rica');
insert into countries values (52, 'CI', 'Cote D\'Ivoire (Ivory Coast)');
insert into countries values (53, 'HR', 'Croatia (Hrvatska)');
insert into countries values (54, 'CU', 'Cuba');
insert into countries values (55, 'CY', 'Cyprus');
insert into countries values (56, 'CZ', 'Czech Republic');
insert into countries values (57, 'DK', 'Denmark');
insert into countries values (58, 'DJ', 'Djibouti');
insert into countries values (59, 'DM', 'Dominica');
insert into countries values (60, 'DO', 'Dominican Republic');
insert into countries values (61, 'TP', 'East Timor');
insert into countries values (62, 'EC', 'Ecuador');
insert into countries values (63, 'EG', 'Egypt');
insert into countries values (64, 'SV', 'El Salvador');
insert into countries values (65, 'GQ', 'Equatorial Guinea');
insert into countries values (66, 'ER', 'Eritrea');
insert into countries values (67, 'EE', 'Estonia');
insert into countries values (68, 'ET', 'Ethiopia');
insert into countries values (69, 'FK', 'Falkland Islands (Malvinas)');
insert into countries values (70, 'FO', 'Faroe Islands');
insert into countries values (71, 'FJ', 'Fiji');
insert into countries values (72, 'FI', 'Finland');
insert into countries values (73, 'FR', 'France');
insert into countries values (74, 'FX', 'France Metropolitan');
insert into countries values (75, 'GF', 'French Guiana');
insert into countries values (76, 'PF', 'French Polynesia');
insert into countries values (77, 'TF', 'French Southern Territories');
insert into countries values (78, 'GA', 'Gabon');
insert into countries values (79, 'GM', 'Gambia');
insert into countries values (80, 'GE', 'Georgia');
insert into countries values (81, 'DE', 'Germany');
insert into countries values (82, 'GH', 'Ghana');
insert into countries values (83, 'GI', 'Gibraltar');
insert into countries values (84, 'GR', 'Greece');
insert into countries values (85, 'GL', 'Greenland');
insert into countries values (86, 'GD', 'Grenada');
insert into countries values (87, 'GP', 'Guadeloupe');
insert into countries values (88, 'GU', 'Guam');
insert into countries values (89, 'GT', 'Guatemala');
insert into countries values (90, 'GN', 'Guinea');
insert into countries values (91, 'GW', 'Guinea-Bissau');
insert into countries values (92, 'GY', 'Guyana');
insert into countries values (93, 'HT', 'Haiti');
insert into countries values (94, 'HM', 'Heard and McDonald Islands');
insert into countries values (95, 'HN', 'Honduras');
insert into countries values (96, 'HK', 'Hong Kong');
insert into countries values (97, 'HU', 'Hungary');
insert into countries values (98, 'IS', 'Iceland');
insert into countries values (99, 'IN', 'India');
insert into countries values (100, 'ID', 'Indonesia');
insert into countries values (101, 'IR', 'Iran');
insert into countries values (102, 'IQ', 'Iraq');
insert into countries values (103, 'IE', 'Ireland');
insert into countries values (104, 'IL', 'Israel');
insert into countries values (105, 'IT', 'Italy');
insert into countries values (106, 'JM', 'Jamaica');
insert into countries values (107, 'JP', 'Japan');
insert into countries values (108, 'JO', 'Jordan');
insert into countries values (109, 'KZ', 'Kazakhstan');
insert into countries values (110, 'KE', 'Kenya');
insert into countries values (111, 'KI', 'Kiribati');
insert into countries values (112, 'KP', 'Korea (North) (People\'s Republic)');
insert into countries values (113, 'KR', 'Korea (South) (Republic)');
insert into countries values (114, 'KW', 'Kuwait');
insert into countries values (115, 'KG', 'Kyrgyzstan (Kyrgyz Republic)');
insert into countries values (116, 'LA', 'Laos');
insert into countries values (117, 'LV', 'Latvia');
insert into countries values (118, 'LB', 'Lebanon');
insert into countries values (119, 'LS', 'Lesotho');
insert into countries values (120, 'LR', 'Liberia');
insert into countries values (121, 'LY', 'Libya');
insert into countries values (122, 'LI', 'Liechtenstein');
insert into countries values (123, 'LT', 'Lithuania');
insert into countries values (124, 'LU', 'Luxembourg');
insert into countries values (125, 'MO', 'Macau');
insert into countries values (126, 'MK', 'Macedonia');
insert into countries values (127, 'MG', 'Madagascar');
insert into countries values (128, 'MW', 'Malawi');
insert into countries values (129, 'MY', 'Malaysia');
insert into countries values (130, 'MV', 'Maldives');
insert into countries values (131, 'ML', 'Mali');
insert into countries values (132, 'MT', 'Malta');
insert into countries values (133, 'MH', 'Marshall Islands');
insert into countries values (134, 'MQ', 'Martinique');
insert into countries values (135, 'MR', 'Mauritania');
insert into countries values (136, 'MU', 'Mauritius');
insert into countries values (137, 'YT', 'Mayotte');
insert into countries values (138, 'MX', 'Mexico');
insert into countries values (139, 'FM', 'Micronesia');
insert into countries values (140, 'MD', 'Moldova');
insert into countries values (141, 'MC', 'Monaco');
insert into countries values (142, 'MN', 'Mongolia');
insert into countries values (143, 'MS', 'Montserrat');
insert into countries values (144, 'MA', 'Morocco');
insert into countries values (145, 'MZ', 'Mozambique');
insert into countries values (146, 'MM', 'Myanmar');
insert into countries values (147, 'NA', 'Namibia');
insert into countries values (148, 'NR', 'Nauru');
insert into countries values (149, 'NP', 'Nepal');
insert into countries values (150, 'NL', 'Netherlands');
insert into countries values (151, 'AN', 'Netherlands Antilles');
insert into countries values (152, 'NT', 'Neutral Zone (Saudia Arabia/Iraq)');
insert into countries values (153, 'NC', 'New Caledonia');
insert into countries values (154, 'NZ', 'New Zealand');
insert into countries values (155, 'NI', 'Nicaragua');
insert into countries values (156, 'NE', 'Niger');
insert into countries values (157, 'NG', 'Nigeria');
insert into countries values (158, 'NU', 'Niue');
insert into countries values (159, 'NF', 'Norfolk Island');
insert into countries values (160, 'MP', 'Northern Mariana Islands');
insert into countries values (161, 'NO', 'Norway');
insert into countries values (162, 'OM', 'Oman');
insert into countries values (163, 'PK', 'Pakistan');
insert into countries values (164, 'PW', 'Palau');
insert into countries values (165, 'PA', 'Panama');
insert into countries values (166, 'PG', 'Papua New Guinea');
insert into countries values (167, 'PY', 'Paraguay');
insert into countries values (168, 'PE', 'Peru');
insert into countries values (169, 'PH', 'Philippines');
insert into countries values (170, 'PN', 'Pitcairn');
insert into countries values (171, 'PL', 'Poland');
insert into countries values (172, 'PT', 'Portugal');
insert into countries values (173, 'PR', 'Puerto Rico');
insert into countries values (174, 'QA', 'Qatar');
insert into countries values (175, 'RE', 'Reunion');
insert into countries values (176, 'RO', 'Romania');
insert into countries values (177, 'RU', 'Russian Federation');
insert into countries values (178, 'RW', 'Rwanda');
insert into countries values (179, 'GS', 'S. Georgia and S. Sandwich Isls.');
insert into countries values (180, 'KN', 'Saint Kitts and Nevis');
insert into countries values (181, 'LC', 'Saint Lucia');
insert into countries values (182, 'VC', 'Saint Vincent and The Grenadines');
insert into countries values (183, 'WS', 'Samoa');
insert into countries values (184, 'SM', 'San Marino');
insert into countries values (185, 'ST', 'Sao Tome and Principe');
insert into countries values (186, 'SA', 'Saudi Arabia');
insert into countries values (187, 'SN', 'Senegal');
insert into countries values (188, 'SC', 'Seychelles');
insert into countries values (189, 'SL', 'Sierra Leone');
insert into countries values (190, 'SG', 'Singapore');
insert into countries values (191, 'SK', 'Slovakia (Slovak Republic)');
insert into countries values (192, 'SI', 'Slovenia');
insert into countries values (193, 'SB', 'Solomon Islands');
insert into countries values (194, 'SO', 'Somalia');
insert into countries values (195, 'ZA', 'South Africa');
insert into countries values (196, 'SU', 'Soviet Union (former)');
insert into countries values (197, 'ES', 'Spain');
insert into countries values (198, 'LK', 'Sri Lanka');
insert into countries values (199, 'SH', 'St. Helena');
insert into countries values (200, 'PM', 'St. Pierre and Miquelon');
insert into countries values (201, 'SD', 'Sudan');
insert into countries values (202, 'SR', 'Suriname');
insert into countries values (203, 'SJ', 'Svalbard and Jan Mayen Islands');
insert into countries values (204, 'SZ', 'Swaziland');
insert into countries values (205, 'SE', 'Sweden');
insert into countries values (206, 'CH', 'Switzerland');
insert into countries values (207, 'SY', 'Syria');
insert into countries values (208, 'TW', 'Taiwan');
insert into countries values (209, 'TJ', 'Tajikistan');
insert into countries values (210, 'TZ', 'Tanzania');
insert into countries values (211, 'TH', 'Thailand');
insert into countries values (212, 'TG', 'Togo');
insert into countries values (213, 'TK', 'Tokelau');
insert into countries values (214, 'TO', 'Tonga');
insert into countries values (215, 'TT', 'Trinidad and Tobago');
insert into countries values (216, 'TN', 'Tunisia');
insert into countries values (217, 'TR', 'Turkey');
insert into countries values (218, 'TM', 'Turkmenistan');
insert into countries values (219, 'TC', 'Turks and Caicos Islands');
insert into countries values (220, 'TV', 'Tuvalu');
insert into countries values (221, 'UG', 'Uganda');
insert into countries values (222, 'UA', 'Ukraine');
insert into countries values (223, 'AE', 'United Arab Emirates');
insert into countries values (224, 'UK', 'United Kingdom (Great Britain)');
insert into countries values (225, 'US', 'United States');
insert into countries values (226, 'UY', 'Uruguay');
insert into countries values (227, 'UM', 'US Minor Outlying Islands');
insert into countries values (228, 'UZ', 'Uzbekistan');
insert into countries values (229, 'VU', 'Vanuatu');
insert into countries values (230, 'VA', 'Vatican City State (Holy See)');
insert into countries values (231, 'VE', 'Venezuela');
insert into countries values (232, 'VN', 'Viet Nam');
insert into countries values (233, 'VG', 'Virgin Islands (British)');
insert into countries values (234, 'VI', 'Virgin Islands (US)');
insert into countries values (235, 'WF', 'Wallis and Futuna Islands');
insert into countries values (236, 'EH', 'Western Sahara');
insert into countries values (237, 'YE', 'Yemen');
insert into countries values (238, 'YU', 'Yugoslavia');
insert into countries values (239, 'ZR', 'Zaire');
insert into countries values (240, 'ZM', 'Zambia');
insert into countries values (241, 'ZW', 'Zimbabwe');